be.api.setvar("return", "1")
if vr("dev") not in be.devices:
    term.write("Camera not initialized.")
else:
    be.api.setvar("return", "1")
    vr("enc", "UTF-8")
    term.write("Reading settings properties..")
    term.write("Initializing buffers..")
    vr("rtsp_str", bytearray(256))
    vr("rtsp_buf", bytearray(8192))
    term.write("Creating RTSP Session..")
    vr("session_id", be.based.run("random"))
    vr("stream_id", 0)
    vr("client_rtp_port", 0)
    vr("client_rtcp_port", 0)
    vr("client", None)
    term.write("Starting up")
    be.api.setvar("return", "0")
